"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[hostname]
disabled = false
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](white) '
aliases = { "Alberts-MacBook-Air" = "air" }

[username]
disabled = false
style_user = 'green bold'
style_root = 'root bold'
format = '[$user]($style)'
show_always = true

[status]
disabled = false
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
